### PR TITLE
Implement XYZ/TMS cached tile service from WMTS

### LINKED ISSUE #16: Migrate web services in Avadepth from WMTS to new XYZ service
Switch Avadepth web services to refer to new XYZ service endpoint for image tiles.

Depends on https://github.com/pspc-spac/avadepth-manager/issues/47

### PR DESCRIPTION
**Pull request by wsidl**
resolves #16 

Add support for changes made in pspc-spac/avadepth-manager#47. Read XYZ tiles in static directory for image source.

### CODE REVIEW

**Comment by wongrm** [comment]
Hi Will, maybe it's my local but it seems like some of the tiles aren't getting pulled in at the closer zoom levels.

image
image

`20706.png:1          GET https://ava-proto.com/tiles/FRSA_Channel_Cells.FRSA_Outline_Cells/GoogleMapsCompatible/17/44953/20706.png 404 (Not Found)
Image (async)
setImgSrc @ OpenLayers.js:494
initImage @ OpenLayers.js:493
renderTile @ OpenLayers.js:489
draw @ OpenLayers.js:489
drawTilesFromQueue @ OpenLayers.js:1352
(anonymous) @ OpenLayers.js:1350
(anonymous) @ OpenLayers.js:63
setTimeout (async)
updateTimeout @ OpenLayers.js:1350
(anonymous) @ OpenLayers.js:1350
(anonymous) @ OpenLayers.js:63
setTimeout (async)
updateTimeout @ OpenLayers.js:1350
(anonymous) @ OpenLayers.js:1350
(anonymous) @ OpenLayers.js:63
setTimeout (async)
updateTimeout @ OpenLayers.js:1350
zoomEnd @ OpenLayers.js:1348
triggerEvent @ OpenLayers.js:138
moveTo @ OpenLayers.js:191
done @ OpenLayers.js:196
stop @ OpenLayers.js:150
play @ OpenLayers.js:151
(anonymous) @ OpenLayers.js:63
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
f.<computed> @ OpenLayers.js:149
requestAnimationFrame (async)
(anonymous) @ OpenLayers.js:149
start @ OpenLayers.js:149
start @ OpenLayers.js:150
zoomTo @ OpenLayers.js:196
zoomOut @ OpenLayers.js:197
onButtonClick @ OpenLayers.js:572
onButtonClick @ OpenLayers.js:579
triggerEvent @ OpenLayers.js:138
buttonClick @ OpenLayers.js:146
triggerEvent @ OpenLayers.js:138
handleBrowserEvent @ OpenLayers.js:138

**Comment by wsidl** [comment]
> Hi Will, maybe it's my local but it seems like some of the tiles aren't getting pulled in at the closer zoom levels.
> 
> image image
> 
> `20706.png:1 GET https://ava-proto.com/tiles/FRSA_Channel_Cells.FRSA_Outline_Cells/GoogleMapsCompatible/17/44953/20706.png 404 (Not Found) Image (async) setImgSrc @ OpenLayers.js:494 initImage @ OpenLayers.js:493 renderTile @ OpenLayers.js:489 draw @ OpenLayers.js:489 drawTilesFromQueue @ OpenLayers.js:1352 (anonymous) @ OpenLayers.js:1350 (anonymous) @ OpenLayers.js:63 setTimeout (async) updateTimeout @ OpenLayers.js:1350 (anonymous) @ OpenLayers.js:1350 (anonymous) @ OpenLayers.js:63 setTimeout (async) updateTimeout @ OpenLayers.js:1350 (anonymous) @ OpenLayers.js:1350 (anonymous) @ OpenLayers.js:63 setTimeout (async) updateTimeout @ OpenLayers.js:1350 zoomEnd @ OpenLayers.js:1348 triggerEvent @ OpenLayers.js:138 moveTo @ OpenLayers.js:191 done @ OpenLayers.js:196 stop @ OpenLayers.js:150 play @ OpenLayers.js:151 (anonymous) @ OpenLayers.js:63 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 f. @ OpenLayers.js:149 requestAnimationFrame (async) (anonymous) @ OpenLayers.js:149 start @ OpenLayers.js:149 start @ OpenLayers.js:150 zoomTo @ OpenLayers.js:196 zoomOut @ OpenLayers.js:197 onButtonClick @ OpenLayers.js:572 onButtonClick @ OpenLayers.js:579 triggerEvent @ OpenLayers.js:138 buttonClick @ OpenLayers.js:146 triggerEvent @ OpenLayers.js:138 handleBrowserEvent @ OpenLayers.js:138

I'll get the tiles copied to the static directory, some may have been missed during testing.

**Comment by wsidl** [comment]
Please try the test again as I've re-copied the missing tiles to the static directory

**Comment by wongrm** [comment]
I just tried and I'm still getting 404s on those tiles when zoomed in close.

**Comment by wongrm** [comment]
Another interesting thing is that the surface isn't even showing up at the highest zoom level: 
image

**Comment by wsidl** [comment]
There does appear to be an issue with the tiles. I found some missing tiles in the static directory which explains the missing imagery. I went to locate the tiles in the SFE Tiles cache and they are also missing. This can only be explained the image generation failed during the tile refresh.

I will add a fix to the Admin Server to capture response statuses and retry the tile request if a non-200 status was found.

If after this fix is implemented and we find the issue still occurs, we may need to investigate if the webserver can use a dual backend proxy for the requests (return static images if found, otherwise send request to SFE to generate tile and copy to static directory).

This work is related to the XYZ/TMS work in the admin portal and bug pspc-spac/avadepth-manager#53 has been created to investigate.

**Comment by wsidl** [comment]
@wongrm I've completed a fix to this issue. It will validate all tile responses to ensure a tile is generated successfully (responds with a HTTP Status 200).

This significantly increased the length for the tiles to generate (~20min to ~70min), but it completed successfully with all missing tiles generated and all tiles were copied automatically to the static directory.

I will perform the task on all remaining layers for your testing.

**Comment by wongrm** [comment]
Hi @wsidl, I'm still getting the exact same issues.

**Comment by wsidl** [comment]
Found the source of the issue. Apparently this also existed with the WMTS service, except what I didn't realize was the map module would cache the tiles from the previous zoom level and uses it for the lowest zoom level. This means the image is a bit blurred, but still visible in the map.

Had to specify which zoom levels the XYZ tiles cover and to enable `alwaysInRange` to ensure the tiles are re-used in the ranges they don't support.

You should be able to continue testing now.

**Pull request merged**
